### ISSUE TITLE
出现了个BUG，本地运行不起来

### ISSUE THREAD

**Issue by QLZL** [VickScarlet/remake#207]
yarn run v1.22.11
$ webpack serve --open /view/index.html
[webpack-cli] D:\git\interesting\lifeRestart\node_modules\webpack-dev-server\lib\servers\WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (D:\git\interesting\lifeRestart\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (D:\git\interesting\lifeRestart\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (D:\git\interesting\lifeRestart\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Server.getServerTransport (D:\git\interesting\lifeRestart\node_modules\webpack-dev-server\lib\Server.js:982:28)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kakazero7** [comment]
+1 大概率是node版本问题 升级一下node吧

**Comment by QLZL** [comment]
好的，谢谢，我试一下
